### PR TITLE
use ember-template-lint from the project

### PR DESCRIPTION
**Pull request by mansona**
This PR fixes the issue where the project you're editing has a different version of ember-template-lint and throws random errors because of the change in the API.

This also makes sure to cater for both ember-template-lint v2 and v3 because the `verify()` now returns a promise

### CODE REVIEW

**Comment by janwerkhoven** [comment]
+1 for merging this PR because it solves this issue too: https://github.com/grrakesh4769/atom-ember-template-lint/issues/86 

Thanks @mansona  🎉

**Comment by grrakesh4769** [comment]
@mansona Thanks a lot!

**Comment by janwerkhoven** [comment]
New release?

**Comment by grrakesh4769** [comment]
@janwerkhoven Also done.

**Comment by janwerkhoven** [comment]
[v4.2.0](https://github.com/grrakesh4769/atom-ember-template-lint/releases/tag/v4.2.0)
nice!

**Comment by janwerkhoven** [comment]
Screen Shot 2021-08-25 at 10 48 32

**Comment by MikiDi** [comment]
Didn't know this had been merged already. Thx @mansona :-)

**Pull request merged**
